---
- hosts: all
  become: true
  tasks:

    - name: Stop nginx service
      service:
        name: nginx
        state: stopped
      ignore_errors: true

    - name: Disable nginx service
      systemd:
        name: nginx
        enabled: no
      ignore_errors: true

    - name: Purge nginx config files
      apt:
        name: nginx*
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: true

    - name: delete nginx config directory
      file:
        path: /etc/nginx
        state: absent
      ignore_errors: true

    - name: stop docker service
      service:
        name: docker
        state: stopped
      ignore_errors: true

    - name: Purge docker packages
      apt:
        name:
          - docker-ce
#          - docker-ce-cli
#          - containerd.io
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: true

    - name: delete files for docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - virtualenv
          - python3-setuptools
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: true

    - name: delete docker config directory 
      file:
        path: /var/lib/docker
        state: absent
      ignore_errors: true

