---
- hosts: all
  become: true
  tasks:

    - name: Reload nginx service (optional)
      service:
        name: nginx
        state: reloaded
      ignore_errors: true

    - name: Stop nginx service
      service:
        name: nginx
        state: stopped
      ignore_errors: true

    - name: Disable nginx service
      systemd:
        name: nginx
        enabled: no
      ignore_errors: true

    - name: Purge nginx packages and config files
      apt:
        name: nginx*
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: true

    - name: Remove nginx config directory (if exists)
      file:
        path: /etc/nginx
        state: absent
      ignore_errors: true

    - name: Stop docker service
      service:
        name: docker
        state: stopped
      ignore_errors: true

    - name: Purge docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: true

    - name: Purge docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - virtualenv
          - python3-setuptools
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: true

    - name: Remove docker config directory (if exists)
      file:
        path: /var/lib/docker
        state: absent
      ignore_errors: true

