---

- hosts: all
  become: true
  tasks:


  - name: install nginx
    apt: 
      name: nginx
      state: latest
      update_cache: yes


  - name: 
        


  - name: Remove default nginx configuration
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: Add nginx configuration
    copy: 
      src: 
      dest:
      owner: root
      group: root
      mode: '0644'

