---

- hosts: all
  become: true
  tasks:


  - name: install nginx
    apt: 
      name: nginx
      state: present
    ignore_errors: true    

        
  - name: systemc daeomon reload
    ansible.builtin.systemd:
      daemon_reload: true
    ignore_errors: true    

    

  - name: Install packets for Docker 
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-requests
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: present

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker repo
    apt_repository:
      repo: deb  https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Install Docker
    apt:
      name: docker-ce
      state: present
      update_cache: true

  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes


  - name: run container 
    community.docker.docker_container:
      name: test
      image: python:3.9-slim
      state: started
      restart_policy: always
      command:  /bin/sh -c "mkdir -p /app && echo salam > /app/index.html && cd /app && python3 -m http.server 8000"
      ports:
        - "8000:8000"

  - name: changes nginx.config 
    copy:
      src: /tmp/nginx_salam.conf
      dest: /etc/nginx/sites-available/salam
      owner: root
      group: root
      mode: '0644'

  - name: crated nginx conf link
    file:
      src: /etc/nginx/sites-available/salam
      dest: /etc/nginx/sites-enabled/salam
      state: link
      force: yes

  - name: delete default nginx conf link
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: reload nginx
    service:
      name: nginx
      state: reloaded

