---

- hosts: all
  become: true
  tasks:


  - name: install nginx
    apt: 
      name: nginx
      state: present
    ignore_errors: true    

  - name: copy nginx.conf from control node
    copy:
      src: /tmp/nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: '0644'
    ignore_errors: true    
        
  - name: systemc daeomon reload
    ansible.builtin.systemd:
      daemon_reload: true
    ignore_errors: true    


  - name: Restart nginx 
    service: 
      name: nginx
      state: restarted
    ignore_errors: true    


  - name: Download container 
    ansible.builtin.apt:  
      name: docker
      state: present
    ignore_errors: true    

  - name: started docker
    service: 
      name: docker.io
      state: started
      enabled: true 
    ignore_errors: true    

  - name: created index html file
    copy: 
      dest: /tmp/index.html
      content: "Salam.Bu ansible ile yaradilmis http serverdir!"
    ignore_errors: true    

  - name: created container
    community.docker.docker_image: 
      name: nginx:latest
      ports: 
        - "80:90"
      volumes: 
        - "/tmp/index.html: /usr/share/nginx/html:ro"
      state: started
    ignore_errors: true    

  - name: install haproxy
    apt:
      name: nginx
      state: present
    ignore_errors: true    

  - name: cp haproxy config file
    copy: 
      src: /tmp/haproxy.cfg 
      dest: /etc/haproxy/haproxy.cfg
      owner: root
      group: root
      mode: '0644'
    ignore_errors: true    

  - name: systemctl daemon-reload
    ansible.builtin.systemd:
      daemon_reload: true
    ignore_errors: true    

  - name: restart haproxy
    service:
      name: haproxy
      state: restarted
    ignore_errors: true    
